services:
  api: &base_api
    build:
      context: .
      dockerfile: ./Dockerfile
    image: api:latest
    container_name: api
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    networks:
      - network

  db:
    image: postgres
    container_name: db
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - network

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
    name: db_data
  bundle_cache:

networks:
  network:
    name: network
    driver: bridge
