services:
  api:
    build:
      context: ../../.
    image: api:${TAG}
    container_name: ${CONTAINER_ENV}-api
    restart: always
    env_file:
      - ../env/${CONTAINER_ENV}.env
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - db
      - redis
    # TODO: Add the correct volumes here to be able to determine which tag/env the volume belongs to
    networks:
      - network

  sidekiq:
    build:
      context: ../../.
    image: api:${TAG}
    container_name: ${CONTAINER_ENV}-sidekiq
    restart: always
    command: bundle exec sidekiq
    env_file:
      - ../env/${CONTAINER_ENV}.env
    depends_on:
      - db
      - redis
    networks:
      - network

  db:
    image: postgres
    container_name: ${CONTAINER_ENV}-db
    env_file:
      - ../env/${CONTAINER_ENV}.env
    ports:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ${CONTAINER_ENV}-db-volume:/var/lib/postgresql/data
    networks:
      - network

  redis:
    image: redis
    container_name: ${CONTAINER_ENV}-redis
    ports:
      - 6379
    volumes:
      - ${CONTAINER_ENV}-redis-volume:/var/lib/redis/data
    networks:
      - network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

# t TODO: This should be done in a less repetative way
volumes:
  develop-db-volume:
    name: ${CONTAINER_ENV}-db-volume
  static-db-volume:
    name: ${CONTAINER_ENV}-db-volume
  staging-db-volume:
    name: ${CONTAINER_ENV}-db-volume
  production-db-volume:
    name: ${CONTAINER_ENV}-db-volume
  develop-redis-volume:
    name: ${CONTAINER_ENV}-redis-volume
  static-redis-volume:
    name: ${CONTAINER_ENV}-redis-volume
  staging-redis-volume:
    name: ${CONTAINER_ENV}-redis-volume
  production-redis-volume:
    name: ${CONTAINER_ENV}-redis-volume

networks:
  network:
    name: ${CONTAINER_ENV}-network
    driver: bridge
