---
openapi: 3.0.1
info:
  title: API V1
  version: v1
  description: API documentation for version 1
paths:
  "/api/v1/articles":
    get:
      summary: list articles
      responses:
        '200':
          description: successful
  "/api/v1/articles/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show article
      responses:
        '200':
          description: successful
  "/api/v1/categories/{category_id}/articles":
    parameters:
    - name: category_id
      in: path
      description: category_id
      required: true
      schema:
        type: string
    get:
      summary: list articles
      responses:
        '200':
          description: successful
  "/api/v1/categories":
    get:
      summary: list categories
      responses:
        '200':
          description: successful
  "/api/v1/categories/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show category
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: http://localhost:3000
