injest_articles_worker:
  every: ['15m', first_in: '0s']
  class: "InjestArticlesWorker"
  queue: default
  description: "Ingests articles from a single RSS feed every 15 minutes"
generate_article_worker:
  class: "GenerateArticleWorker"
  queue: default
  description: "Generates articles based on available feed entries"
